version: '3.7'

services:

  service-a:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    environment:
      - PORT=3000
      - TZ=America/Los_Angeles
    ports:
      - 4000:3000
    command: nx serve service-a

  service-b:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    environment:
      - PORT=3000
    ports:
      - 4001:3000
    command: nx serve service-b
